import type { CapabilityDefinition } from './types.js';

export const CORE_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'runtime/dotnet',
    version: '1.0.0',
    kind: 'runtime',
    support: 'verified',
    provides: ['runtime:dotnet'],
    requires: [],
    conflicts: [],
    runtimeRequirements: [{ name: 'dotnet', minVersion: '10.0.0' }],
    dependencies: [],
  },
  {
    id: 'runtime/node',
    version: '1.0.0',
    kind: 'runtime',
    support: 'verified',
    provides: ['runtime:node'],
    requires: [],
    conflicts: [],
    runtimeRequirements: [{ name: 'node', minVersion: '22.13.0' }],
    dependencies: [],
  },
  {
    id: 'runtime/python',
    version: '1.0.0',
    kind: 'runtime',
    support: 'verified',
    provides: ['runtime:python'],
    requires: [],
    conflicts: [],
    runtimeRequirements: [{ name: 'python', minVersion: '3.13.0' }],
    dependencies: [],
  },
  {
    id: 'backend/aspnet-core',
    version: '1.0.0',
    kind: 'framework',
    support: 'verified',
    provides: ['backend:framework'],
    requires: [{ target: 'runtime:dotnet' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/dotnet' }],
  },
  {
    id: 'backend/fastify',
    version: '1.0.0',
    kind: 'framework',
    support: 'verified',
    provides: ['backend:framework'],
    requires: [{ target: 'runtime:node' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/node' }],
  },
  {
    id: 'backend/express',
    version: '1.0.0',
    kind: 'framework',
    support: 'verified',
    provides: ['backend:framework'],
    requires: [{ target: 'runtime:node' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/node' }],
  },
  {
    id: 'backend/fastapi',
    version: '1.0.0',
    kind: 'framework',
    support: 'verified',
    provides: ['backend:framework'],
    requires: [{ target: 'runtime:python' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/python' }],
  },
  {
    id: 'architecture/clean',
    version: '1.0.0',
    kind: 'architecture',
    support: 'verified',
    provides: ['backend:architecture'],
    requires: [{ target: 'backend:framework' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'architecture/modular',
    version: '1.0.0',
    kind: 'architecture',
    support: 'verified',
    provides: ['backend:architecture'],
    requires: [{ target: 'backend:framework' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'architecture/blank',
    version: '1.0.0',
    kind: 'architecture',
    support: 'verified',
    provides: ['backend:architecture'],
    requires: [{ target: 'backend:framework' }],
    conflicts: [
      { target: 'database/postgresql' },
      { target: 'database/mysql' },
      { target: 'database/sqlserver' },
      { target: 'database/sqlite' },
      { target: 'database/mongodb' },
    ],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/postgresql',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [{ target: 'architecture/blank' }],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/sqlserver',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [{ target: 'architecture/blank' }],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/mysql',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [{ target: 'architecture/blank' }],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/sqlite',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [{ target: 'architecture/blank' }],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/mongodb',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [{ target: 'architecture/blank' }],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'database/none',
    version: '1.0.0',
    kind: 'database',
    support: 'verified',
    provides: ['persistence:database'],
    requires: [],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [],
  },
  {
    id: 'frontend/react',
    version: '1.0.0',
    kind: 'frontend',
    support: 'verified',
    provides: ['frontend:ui'],
    requires: [{ target: 'runtime:node' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/node' }],
  },
  {
    id: 'frontend/vue',
    version: '1.0.0',
    kind: 'frontend',
    support: 'verified',
    provides: ['frontend:ui'],
    requires: [{ target: 'runtime:node' }],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [{ id: 'runtime/node' }],
  },
  {
    id: 'frontend/none',
    version: '1.0.0',
    kind: 'frontend',
    support: 'verified',
    provides: ['frontend:ui'],
    requires: [],
    conflicts: [],
    runtimeRequirements: [],
    dependencies: [],
  },
];
