import { ProjectConfig } from '../types.js';

export function generateCompositeGitignore(config: ProjectConfig): string {
  let content = `# ==============================================================================
# UNIVERSAL COMPOSITE .GITIGNORE (Auto-generated by create-p-stack)
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. CRITICAL: ZERO-LEAKAGE SECURITY & SECRETS (NON-NEGOTIABLE)
# ------------------------------------------------------------------------------
.env
.env.*
!.env.example
*.pem
*.key
*.pfx
*.cert

# ------------------------------------------------------------------------------
# 2. Operating System & Editor Files
# ------------------------------------------------------------------------------
.DS_Store
Thumbs.db
desktop.ini
.idea/
.vscode/*
!.vscode/extensions.json
!.vscode/settings.json

# ------------------------------------------------------------------------------
# 3. Node.js & Monorepo Dependencies & Logs
# ------------------------------------------------------------------------------
node_modules/
.pnpm-store/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
dist/
build/
out/
`;

  // Backend specific rules
  if (config.backend.type === 'dotnet') {
    content += `
# ------------------------------------------------------------------------------
# 4. .NET 8 / C# Artifacts
# ------------------------------------------------------------------------------
bin/
obj/
*.user
*.suo
*.userosscache
*.sln.docstates
appsettings.Development.json
*.db
*.db-shm
*.db-wal
`;
  } else if (config.backend.type === 'fastapi') {
    content += `
# ------------------------------------------------------------------------------
# 4. Python & FastAPI Artifacts
# ------------------------------------------------------------------------------
__pycache__/
*.py[cod]
*$py.class
.venv/
env/
venv/
.pytest_cache/
*.egg-info/
*.db
`;
  }

  // Frontend specific rules
  if (config.frontend.type === 'nextjs') {
    content += `
# ------------------------------------------------------------------------------
# 5. Next.js Artifacts
# ------------------------------------------------------------------------------
.next/
`;
  } else if (config.frontend.type === 'nuxt3') {
    content += `
# ------------------------------------------------------------------------------
# 5. Nuxt 3 Artifacts
# ------------------------------------------------------------------------------
.nuxt/
.output/
`;
  }

  return content.trim() + '\n';
}
